import './calculator-ui.mjs';
document.documentElement.classList.add('js');const $=s=>document.querySelector(s);
const esc=v=>String(v??'');function link(url,label){const a=document.createElement('a');if(url?.startsWith('downloads/')){a.href='#downloads';a.dataset.auditFile=url.slice(10);}else a.href=url||'#';a.textContent=label||'원문 보기';a.target='_blank';a.rel='noopener noreferrer';return a}
function render(data){const timeline=$('#timeline-list');timeline.replaceChildren();(data.timeline||[]).forEach(item=>{const article=document.createElement('article');article.className='timeline-item';const date=document.createElement('div');date.className='timeline-date';date.textContent=esc(item.date||'날짜 미확보');const badge=document.createElement('span');badge.className=`badge ${esc(item.status||'pending')}`;badge.textContent=item.status==='official'?'공식 확인':item.status==='provided'?'제공 자료':'날짜 미확보';date.append(badge);const h=document.createElement('h3');h.textContent=esc(item.title);const p=document.createElement('p');p.textContent=esc(item.body);article.dataset.phase=esc(item.state);article.append(date,h,p);if(item.sourceUrl){const a=link(item.sourceUrl,item.sourceLabel||'출처');a.className='source-link';article.append(a)}timeline.append(article)});if(!timeline.children.length)timeline.innerHTML='<p class="loading">타임라인 자료를 준비 중입니다.</p>';
const sources=$('#sources-list');sources.replaceChildren();(data.sources||[]).forEach(s=>{const row=document.createElement('div');row.className='source-item';const t=document.createElement('span'),strong=document.createElement('strong'),detail=document.createElement('small');strong.textContent=esc(s.id)+' · '+esc(s.title);detail.textContent=esc(s.detail||'');t.append(strong,document.createElement('br'),detail);row.append(t,link(s.url,'출처 보기'));sources.append(row)});if(!sources.children.length)sources.innerHTML='<p class="loading">근거 자료를 준비 중입니다.</p>';
const downloads=$('#download-list');downloads.replaceChildren();(data.downloads||[]).forEach(d=>{const card=document.createElement('div');card.className='download-card';const info=document.createElement('div');const strong=document.createElement('strong');strong.textContent=esc(d.title);const span=document.createElement('span');span.textContent=`${esc(d.pages||'')}쪽`;info.append(strong,span);const links=document.createElement('div');if(d.pdf)links.append(link(d.pdf,'PDF'));if(d.pptx){if(links.childNodes.length)links.append(' · ');links.append(link(d.pptx,'PPTX'))}card.append(info,links);downloads.append(card)});if(!downloads.children.length)downloads.innerHTML='<p class="loading">국감 자료를 준비 중입니다.</p>';
if(data.quote?.text){const q=$('#quote');q.querySelector('p').textContent=`“${esc(data.quote.text)}”`;if(data.quote.context){const cite=q.querySelector('cite'),existing=cite.querySelector('a'),url=data.quote.url||existing?.href||'#';cite.replaceChildren();const context=document.createElement('span');context.textContent=esc(data.quote.context)+' · 1:10:07–1:10:10 · ';cite.append(context,link(url,'원본 영상'))}} }
fetch('data.json').then(r=>{if(!r.ok)throw Error('pending');return r.json()}).then(data=>{render(data);$('#data-status').textContent='공식 공고 · 제공 자료 · 원문 미확보 항목을 구분했습니다.'}).catch(()=>{$('#data-status').textContent='저장된 본문을 표시하고 있습니다. 모든 출처와 파일 링크는 아래에서 확인할 수 있습니다.'});
addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;$('.reading-progress span').style.width=`${max?scrollY/max*100:0}%`},{passive:true});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add('is-visible')),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
