import {floor,catalog,item,newProject,validateProject,uid,corners,issues} from './planner-model.mjs';
import * as store from './planner-store.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],svg=$('#plan-svg'),viewport=$('#viewport'),dialog=$('#planner-dialog');
let project=newProject(),user=null,readonly=false,selected=null,mode='2d',three=null,view=[-550,-550,13100,9900],history=[],future=[],pendingType=null,measure=false,measurePoints=[],positioning=false,category='all',lowWalls=true,localTimer,cloudTimer,saving=Promise.resolve(),authEpoch=0;
const clone=x=>structuredClone(x),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function button(text,fn,cls='soft-button'){const e=el('button',text,cls);e.type='button';e.onclick=async()=>{try{await fn();}catch(error){fail(error);}};return e;}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),4500);}
function fail(e){toast(e.message||'처리하지 못했습니다. 다시 시도해 주세요.');console.warn(e.message);}
function status(s){$('#save-status').textContent=s;}
function modal(title){$('#dialog-title').textContent=title;const body=$('#dialog-body');body.replaceChildren();if(!dialog.open)dialog.showModal();return body;}
function field(label,type,value){const l=el('label',label,'field-label'),i=el(type==='textarea'?'textarea':'input');if(type!=='textarea')i.type=type;i.value=value??'';l.append(i);return [l,i];}
function selectedItem(){return project.items.find(i=>i.id===selected);}
function remember(){history.push(clone(project));if(history.length>50)history.shift();future=[];}
function change(fn){if(readonly)return toast('공유본은 보기 전용입니다. 내 배치로 복사해 주세요.');const before=clone(project);try{fn();validateProject(project);}catch(e){project=before;throw e;}history.push(before);if(history.length>50)history.shift();future=[];refresh();schedule();}
function schedule(){if(readonly)return;project.pendingSync=true;clearTimeout(localTimer);clearTimeout(cloudTimer);status('저장 중…');localTimer=setTimeout(localSave,1000);cloudTimer=setTimeout(()=>cloudSave().catch(fail),3000);}
function localSave(){if(readonly)return;try{validateProject(project);store.saveDraft(user,project);status(user?'기기에 저장됨 · 계정 저장 대기':'이 기기에만 저장됨');}catch(e){status('기기 저장 실패 · 내보내기로 보관');fail(e);}}
function cloudSave(){
 if(readonly)return Promise.resolve();localSave();if(!user)return Promise.resolve();
 const owner=user,epoch=authEpoch,snapshot=clone(project);
 saving=saving.catch(()=>{}).then(async()=>{
  if(epoch!==authEpoch||user?.id!==owner.id)return;
  const sent=project.id===snapshot.id?clone(project):snapshot;
  status('계정에 저장 중…');
  try{
   const r=await store.savePlan(sent);if(epoch!==authEpoch)return;
   if(r.conflict){const copy={...sent,id:uid(),revision:0,title:sent.title.slice(0,60)+' · 충돌 사본'};const saved=await store.savePlan(copy);copy.revision=saved.revision;copy.pendingSync=false;store.saveDraft(owner,copy);if(project.id===sent.id){const newer=clone(project);project={...newer,id:copy.id,revision:copy.revision};if(JSON.stringify(newer)===JSON.stringify(sent))project.pendingSync=false;}toast('다른 기기의 수정본을 보호하기 위해 사본으로 저장했습니다.');}
   else {sent.revision=r.revision;sent.pendingSync=false;if(project.id===sent.id){const unchanged=JSON.stringify({...project,revision:sent.revision,pendingSync:false})===JSON.stringify(sent);project.revision=r.revision;if(unchanged)project.pendingSync=false;store.saveDraft(owner,project);}else store.saveDraft(owner,sent);}
   status(project.pendingSync?'기기에 저장됨 · 계정 저장 대기':'계정에 저장됨');
  }catch(e){status('저장 실패 · 기기에 보존됨');throw e;}
 });return saving;
}
function flush(){clearTimeout(localTimer);clearTimeout(cloudTimer);localSave();}
function setProject(p){clearTimeout(localTimer);clearTimeout(cloudTimer);validateProject(p);project=clone(p);selected=null;history=[];future=[];measurePoints=[];pendingType=null;$('#project-name').value=project.title;fit();refresh();status(readonly?'공유본 · 보기 전용':'이 기기에만 저장됨');}
function rectPoly(points){return points.map(p=>p.join(',')).join(' ');}
function text(x,y,value,size=170,fill='#334155'){return `<text x="${x}" y="${y}" text-anchor="middle" font-family="Arial, sans-serif" font-size="${size}" fill="${fill}">${escape(value)}</text>`;}
function doorPoints(d){const r=d.angle*Math.PI/180,pts=[[d.x,d.y]];for(let k=0;k<=12;k++){const a=r+k*Math.PI/24;pts.push([d.x+Math.cos(a)*d.width,d.y+Math.sin(a)*d.width]);}return pts;}
function render(){svg.setAttribute('viewBox',view.join(' '));svg.innerHTML=`<defs><pattern id="grid" width="500" height="500" patternUnits="userSpaceOnUse"><path d="M 500 0 L 0 0 0 500" fill="none" stroke="#dfe5eb" stroke-width="12"/></pattern></defs><rect x="-100000" y="-100000" width="200000" height="200000" fill="#f6f8fa"/><rect x="0" y="0" width="12000" height="8800" fill="url(#grid)"/>`;
 let out='';for(const r of floor.rooms){out+=`<polygon points="${rectPoly(r.polygon)}" fill="${r.color}" stroke="#ccd3d9" stroke-width="18"/>`;const xs=r.polygon.map(p=>p[0]),ys=r.polygon.map(p=>p[1]);out+=text((Math.min(...xs)+Math.max(...xs))/2,(Math.min(...ys)+Math.max(...ys))/2,r.name);}
 for(const w of floor.walls)out+=`<line x1="${w.a[0]}" y1="${w.a[1]}" x2="${w.b[0]}" y2="${w.b[1]}" stroke="#657786" stroke-width="${w.thickness}" stroke-linecap="square"/>`;
 for(const w of floor.windows)out+=`<line x1="${w.a[0]}" y1="${w.a[1]}" x2="${w.b[0]}" y2="${w.b[1]}" stroke="#44a7cc" stroke-width="65"/>`;
 if($('#doors').checked)for(const d of floor.doors)out+=`<polygon points="${rectPoly(doorPoints(d))}" fill="#e2b779" fill-opacity=".25" stroke="#b5894e" stroke-width="20" stroke-dasharray="50 30"/>`;
 for(const f of floor.fixtures)out+=`<rect x="${f.x-f.w/2}" y="${f.y-f.d/2}" width="${f.w}" height="${f.d}" rx="40" fill="${f.color}" stroke="#96a4a9" stroke-width="20"/>`;
 project.items.forEach((i,n)=>{const warn=issues(i,project.items).length>0;out+=`<g data-item="${escape(i.id)}" transform="translate(${i.x} ${i.y}) rotate(${i.rotation})" style="cursor:${readonly?'default':'move'}"><rect x="${-i.w/2}" y="${-i.d/2}" width="${i.w}" height="${i.d}" rx="${i.type==='round-table'?Math.min(i.w,i.d)/2:55}" fill="${i.color}" stroke="${i.id===selected?'#1567bf':warn?'#ad5b32':'#526779'}" stroke-width="${i.id===selected?65:25}"/>`;
 if(i.type==='bed')out+=`<rect x="${-i.w*.4}" y="${-i.d*.4}" width="${i.w*.8}" height="${i.d*.2}" rx="60" fill="#f8f5f1"/>`;
 if(i.type.includes('sofa'))out+=`<path d="M ${-i.w*.4} ${i.d*.3} V ${-i.d*.3} H ${i.w*.4} V ${i.d*.3}" fill="none" stroke="#ffffff88" stroke-width="110"/>`;
 out+=text(0,Math.min(80,i.d*.2),`${n+1}. ${i.name}`,Math.min(170,Math.max(90,i.w/7)),'#172e40')+'</g>';});
 const i=selectedItem();if(i){const pts=corners(i),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]);const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const left=floor.walls.filter(w=>w.a[0]===w.b[0]&&w.a[0]<=minX&&Math.min(w.a[1],w.b[1])<=i.y&&Math.max(w.a[1],w.b[1])>=i.y).map(w=>w.a[0]+w.thickness/2);const right=floor.walls.filter(w=>w.a[0]===w.b[0]&&w.a[0]>=maxX&&Math.min(w.a[1],w.b[1])<=i.y&&Math.max(w.a[1],w.b[1])>=i.y).map(w=>w.a[0]-w.thickness/2);for(const [edge,wall] of [[minX,Math.max(0,...left)],[maxX,Math.min(12000,...right)]]){out+=`<line x1="${edge}" y1="${i.y}" x2="${wall}" y2="${i.y}" stroke="#1767a1" stroke-width="18" stroke-dasharray="40 30"/>`+text((edge+wall)/2,i.y-110,`${Math.max(0,Math.round(Math.abs(edge-wall)/10))}cm`,140,'#145b8f');}
 out+=text(i.x,maxY+260,`${Math.round(i.w/10)} × ${Math.round(i.d/10)}cm`,160);}
 if(measurePoints.length){out+=`<circle cx="${measurePoints[0][0]}" cy="${measurePoints[0][1]}" r="70" fill="#d95437"/>`;if(measurePoints.length===2){const [a,b]=measurePoints;out+=`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" stroke="#d95437" stroke-width="30"/>`+text((a[0]+b[0])/2,(a[1]+b[1])/2-180,`${(Math.hypot(a[0]-b[0],a[1]-b[1])/10).toFixed(1)}cm`,190,'#a33122');}}
 if($('#cad-overlay').checked)out+='<image href="assets/planner-52a-cad-walls.svg" x="0" y="0" width="12000" height="8800" pointer-events="none"/>';svg.insertAdjacentHTML('beforeend',out);$('#zoom-level').textContent=Math.round(13100/view[2]*100)+'%';}
function refresh(){$('#empty-hint').hidden=project.items.length>0||readonly;render();renderInspector();renderItems();$('#project-name').value=project.title;$('#project-name').disabled=readonly;$$('[data-action="undo"]').forEach(b=>b.disabled=readonly||!history.length);$$('[data-action="redo"]').forEach(b=>b.disabled=readonly||!future.length);if(three&&mode==='3d')three.update(project);}
function fit(){view=[-550,-550,13100,9900];$('#room-select').value='all';render();if(three)three.focusRoom(null);}
function focusRoom(){const r=floor.rooms.find(r=>r.id===$('#room-select').value);if(!r)return fit();const xs=r.polygon.map(p=>p[0]),ys=r.polygon.map(p=>p[1]);view=[Math.min(...xs)-500,Math.min(...ys)-500,Math.max(...xs)-Math.min(...xs)+1000,Math.max(...ys)-Math.min(...ys)+1000];render();three?.focusRoom(r);}
function zoom(f){const [x,y,w,h]=view;view=[x+w*(1-f)/2,y+h*(1-f)/2,Math.max(1200,Math.min(25000,w*f)),Math.max(1000,Math.min(19000,h*f))];render();}
function select(id,open=true){selected=id;render();renderInspector();if(open&&!readonly)$('#inspector').classList.add('is-open');}
function renderItems(){const l=$('#furniture-list');l.classList.remove('sr-only');l.replaceChildren(el('h2',`배치한 가구 ${project.items.length}/100`));for(const [n,i] of project.items.entries())l.append(button(`${n+1}. ${i.name}${i.locked?' · 잠김':''}`,()=>{show2D();select(i.id);},'item-list-button'));if(!project.items.length)l.append(el('p','가구를 추가하면 여기서도 선택할 수 있어요.'));}
function renderCatalog(){const l=$('#catalog-list'),q=$('#catalog-search').value.trim();l.replaceChildren();const cats={living:'거실',bedroom:'침실',dining:'주방'};for(const c of catalog.filter(c=>(category==='all'||c.category===cats[category])&&c.name.includes(q))){const b=button('',()=>beginAdd(c.type),'catalog-card');b.innerHTML=`<span class="furniture-icon" aria-hidden="true">${c.type==='bed'?'▰':c.type.includes('sofa')?'▤':c.type==='round-table'?'◯':'▱'}</span><strong>${c.name}</strong><small>${c.w/10} × ${c.d/10}cm · 예시</small>`;l.append(b);}}
function beginAdd(type){if(readonly)return toast('내 배치로 복사하면 수정할 수 있습니다.');if(project.items.length>=100)return toast('가구는 100개까지 배치할 수 있습니다.');pendingType=type;show2D();$('#catalog').classList.remove('is-open');toast('도면에서 가구를 놓을 위치를 눌러 주세요.');viewport.scrollIntoView({block:'center',behavior:'smooth'});}
function renderInspector(){const p=$('#selection-fields');p.replaceChildren();const i=selectedItem();if(!i){p.append(el('p','도면이나 아래 목록에서 가구를 선택하세요.'));return;}p.append(el('h3',i.name));const warnings=issues(i,project.items);if(warnings.length)p.append(el('p','배치 확인 필요: '+warnings.join(' · '),'warning'));if(readonly){p.append(el('p',`${i.w/10} × ${i.d/10} × ${i.h/10}cm · 보기 전용`));return;}
 const form=el('form');const fields={};for(const [key,label,type,value] of [['name','가구 이름','text',i.name],['w','가로 (cm)','number',i.w/10],['d','깊이 (cm)','number',i.d/10],['h','높이 (cm)','number',i.h/10],['rotation','회전 (도)','number',i.rotation],['color','색상','color',i.color],['url','제품 링크 (선택)','url',i.url],['note','개인 메모 (선택)','textarea',i.note]]){const [l,input]=field(label,type,value);fields[key]=input;if(type==='number'){input.step=key==='rotation'?'1':'0.1';input.min=key==='rotation'?'-360':'1';input.max=key==='rotation'?'360':key==='h'?'400':'1000';}if(key==='name'){input.required=true;input.maxLength=80;}if(key==='note')input.maxLength=1000;if(key==='url')input.maxLength=2000;input.disabled=i.locked;form.append(l);}
 if(i.type==='bed'){const preset=el('select');preset.setAttribute('aria-label','침대 크기 예시');preset.innerHTML='<option value="">침대 크기 예시 선택</option><option value="110,210">싱글 프레임 예시</option><option value="120,210">슈퍼싱글 프레임 예시</option><option value="160,210">퀸 프레임 예시</option><option value="180,210">킹 프레임 예시</option>';preset.disabled=i.locked;preset.onchange=()=>{if(preset.value){const [w,d]=preset.value.split(',');fields.w.value=w;fields.d.value=d;}};form.prepend(preset);form.append(el('small','제품별 외곽 크기가 다릅니다. 실제 치수를 입력하세요.'));}
 const apply=el('button','치수 적용','primary-button');apply.type='submit';apply.disabled=i.locked;form.append(apply);form.onsubmit=e=>{e.preventDefault();try{const next={...i};for(const [k,v]of Object.entries(fields))next[k]=['w','d','h'].includes(k)?Number(v.value)*10:k==='rotation'?Number(v.value):v.value.trim();validateProject({...project,items:project.items.map(x=>x.id===i.id?next:x)});change(()=>Object.assign(i,next));toast('가구 치수를 적용했습니다.');}catch(e){fail(e);}};p.append(form);
 const ops=el('div',undefined,'edit-actions');ops.append(button('90° 회전',()=>{if(i.locked)return;change(()=>i.rotation=(i.rotation+90)%360);}),button('위치 지정',()=>{if(i.locked)return;positioning=true;$('#inspector').classList.remove('is-open');toast('새 위치를 눌러 주세요.');}),button('복제',()=>{if(project.items.length>=100)return toast('100개까지 가능합니다.');change(()=>{const copy={...clone(i),id:uid(),x:i.x+150,y:i.y+150,locked:false};project.items.push(copy);selected=copy.id;});}),button(i.locked?'잠금 해제':'잠금',()=>change(()=>i.locked=!i.locked)),button('삭제',()=>{if(i.locked)return toast('잠금을 먼저 해제해 주세요.');change(()=>{project.items=project.items.filter(x=>x.id!==i.id);selected=null;});}));p.append(ops);const arrows=el('div',undefined,'edit-actions');for(const [label,dx,dy]of [['←',-10,0],['↑',0,-10],['↓',0,10],['→',10,0]])arrows.append(button(label+' 1cm',()=>{if(!i.locked)change(()=>{i.x+=dx;i.y+=dy;});}));p.append(arrows);const align=el('div',undefined,'edit-actions');for(const [name,axis,dir]of [['왼쪽 벽',0,-1],['오른쪽 벽',0,1],['위쪽 벽',1,-1],['아래쪽 벽',1,1]])align.append(button(name+' 맞춤',()=>{if(i.locked)return;const other=1-axis,pts=corners(i),edge=dir<0?Math.min(...pts.map(p=>p[axis])):Math.max(...pts.map(p=>p[axis])),center=other===0?i.x:i.y;const walls=floor.walls.filter(w=>w.a[axis]===w.b[axis]&&Math.min(w.a[other],w.b[other])<=center&&Math.max(w.a[other],w.b[other])>=center).map(w=>w.a[axis]-dir*w.thickness/2).filter(v=>dir<0?v<=edge:v>=edge);if(!walls.length)return toast('해당 방향에서 벽을 찾지 못했습니다.');const target=dir<0?Math.max(...walls):Math.min(...walls);change(()=>i[axis===0?'x':'y']+=target-edge);}));p.append(align);} 
function show2D(){mode='2d';svg.removeAttribute('hidden');$('#three-view').hidden=true;$$('[data-action="view-2d"]').forEach(b=>{b.classList.add('active');b.setAttribute('aria-pressed','true');});$$('[data-action="view-3d"]').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false');});}
async function show3D(){try{if(!three){const {create3D}=await import('./planner-3d.mjs?v=2');$('#three-view').hidden=false;three=await create3D($('#three-view'),floor,id=>{show2D();select(id);});}mode='3d';svg.setAttribute('hidden','');$('#three-view').hidden=false;three.update(project);three.setLowWalls(lowWalls);three.resize();focusRoom();$$('[data-action="view-2d"]').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false');});$$('[data-action="view-3d"]').forEach(b=>{b.classList.add('active');b.setAttribute('aria-pressed','true');});}catch(e){show2D();toast('이 환경에서는 3D를 열지 못했습니다. 2D 배치와 저장은 계속 이용할 수 있습니다.');console.error(e);}}
function point(e){const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse());return [p.x,p.y];}
const pointers=new Map();let drag=null,pinch=null;
svg.style.touchAction='none';svg.onpointerdown=e=>{if(mode!=='2d')return;svg.setPointerCapture(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2){if(drag?.before){project=drag.before;refresh();}drag=null;const [a,b]=[...pointers.values()];pinch={distance:Math.hypot(a[0]-b[0],a[1]-b[1]),mid:[(a[0]+b[0])/2,(a[1]+b[1])/2],view:[...view]};return;}const id=e.target.closest('[data-item]')?.dataset.item;const i=project.items.find(i=>i.id===id);drag={client:[e.clientX,e.clientY],start:point(e),view:[...view],id,original:i?{x:i.x,y:i.y}:null,before:i&&!readonly&&!i.locked?clone(project):null,moved:false};};
svg.onpointermove=e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size>=2&&pinch){const [a,b]=[...pointers.values()],dist=Math.max(1,Math.hypot(a[0]-b[0],a[1]-b[1])),f=Math.max(.15,Math.min(3,pinch.distance/dist)),[x,y,w,h]=pinch.view,r=svg.getBoundingClientRect(),mid=[(a[0]+b[0])/2,(a[1]+b[1])/2];view=[x+w*(1-f)/2-(mid[0]-pinch.mid[0])*w/r.width,y+h*(1-f)/2-(mid[1]-pinch.mid[1])*h/r.height,w*f,h*f];render();return;}if(!drag)return;const delta=Math.hypot(e.clientX-drag.client[0],e.clientY-drag.client[1]);if(delta<5&&!drag.moved)return;drag.moved=true;if(drag.before){selected=drag.id;const i=selectedItem(),p=point(e),snap=$('#snap').checked?50:1;i.x=Math.max(-1000,Math.min(13000,Math.round((drag.original.x+p[0]-drag.start[0])/snap)*snap));i.y=Math.max(-1000,Math.min(9800,Math.round((drag.original.y+p[1]-drag.start[1])/snap)*snap));render();}else if(!drag.id){const r=svg.getBoundingClientRect();view=[drag.view[0]-(e.clientX-drag.client[0])*drag.view[2]/r.width,drag.view[1]-(e.clientY-drag.client[1])*drag.view[3]/r.height,drag.view[2],drag.view[3]];render();}};
function pointerEnd(e,cancel=false){const wasPinch=!!pinch;pointers.delete(e.pointerId);if(wasPinch){if(pointers.size===0)pinch=null;drag=null;return;}if(!drag)return;const d=drag;drag=null;if(cancel){if(d.before){project=d.before;refresh();}return;}if(d.moved){if(d.before){history.push(d.before);if(history.length>50)history.shift();future=[];refresh();schedule();}return;}const [x,y]=point(e);if(measure){if(measurePoints.length===2)measurePoints=[];measurePoints.push([x,y]);render();return;}if(pendingType){const type=pendingType;pendingType=null;change(()=>{const i=item(type,x,y);project.items.push(i);selected=i.id;});$('#inspector').classList.add('is-open');return;}if(positioning&&selectedItem()){positioning=false;change(()=>{selectedItem().x=x;selectedItem().y=y;});return;}select(d.id||null,!!d.id);}
svg.onpointerup=e=>pointerEnd(e);svg.onpointercancel=e=>pointerEnd(e,true);svg.onwheel=e=>{e.preventDefault();zoom(e.deltaY>0?1.1:.9);};
async function login(){if(!user){const body=modal('계정 저장·공유 준비 중');body.append(el('p','인증번호 이메일 발송 연결을 준비하고 있습니다. 현재 배치는 이 기기에 저장되며, 편집 파일로 내보내 다른 기기로 옮길 수 있습니다.'),button('편집 파일 내보내기',exports));return;}if(user){const b=modal('계정');b.append(el('p',user.email||'로그인됨'),button('로그아웃',async()=>{flush();await saving.catch(()=>{});await store.auth.auth.signOut();dialog.close();}));return;}const b=modal('이메일로 로그인');b.append(el('p','이메일로 받은 인증번호를 입력하면 다른 기기에서도 배치를 이어갈 수 있어요.'));const [l,email]=field('이메일','email','');email.required=true;const f=el('form');f.append(l);const send=el('button','인증번호 받기','primary-button');send.type='submit';f.append(send);b.append(f);f.onsubmit=async e=>{e.preventDefault();send.disabled=true;try{await store.requestCode(email.value.trim());const [cl,code]=field('이메일 인증번호','text','');code.inputMode='numeric';code.autocomplete='one-time-code';code.required=true;const cf=el('form');cf.append(cl);const verify=el('button','로그인','primary-button');verify.type='submit';cf.append(verify);b.replaceChildren(el('p','이메일의 인증번호를 입력해 주세요. 스팸함도 확인해 주세요.'),cf);cf.onsubmit=async e=>{e.preventDefault();verify.disabled=true;try{await store.verifyCode(email.value.trim(),code.value.trim());dialog.close();toast('로그인했습니다. 저장 버튼으로 현재 배치를 계정에 보관하세요.');}catch(e){fail(e);verify.disabled=false;}};}catch(e){send.disabled=false;fail(e);}};}
async function projects(){flush();const b=modal('내 배치');b.append(el('p',user?'계정에 저장된 배치와 이 기기의 임시 저장을 확인하세요.':'현재 기기에 저장된 배치입니다. 다른 기기에서는 로그인 저장이 필요합니다.'));let list=store.drafts(user);if(user){try{const cloud=await store.listPlans();const map=new Map(cloud.map(r=>[r.id,{...r.data,id:r.id,revision:r.revision,cloudUpdatedAt:r.updated_at}]));for(const d of list){const c=map.get(d.id);if(!c||d.pendingSync)map.set(d.id,d);}list=[...map.values()];}catch(e){b.append(el('p','계정 목록을 불러오지 못했습니다. 기기 저장본을 표시합니다.'));}}
 if(!list.length)b.append(el('p','아직 저장한 배치가 없습니다.'));for(const p of list){const card=el('article',undefined,'project-card');const preview=document.createElementNS('http://www.w3.org/2000/svg','svg');preview.setAttribute('viewBox','0 0 12000 8800');preview.setAttribute('aria-label',p.title+' 미리보기');preview.innerHTML=floor.rooms.map(r=>`<polygon points="${rectPoly(r.polygon)}" fill="${r.color}" stroke="#7f8e9a" stroke-width="50"/>`).join('')+p.items.map(i=>`<polygon points="${rectPoly(corners(i))}" fill="${/^#[a-f0-9]{6}$/i.test(i.color)?i.color:'#8b9bb1'}"/>`).join('');card.append(preview,el('h3',p.title),el('p',`가구 ${p.items.length}개 · ${new Date(p.localUpdatedAt||p.cloudUpdatedAt||Date.now()).toLocaleString('ko-KR')}`));card.append(button('열기',()=>{readonly=false;setProject(p);dialog.close();}),button('복제',()=>{readonly=false;setProject({...clone(p),id:uid(),revision:0,title:p.title.slice(0,65)+' · 사본'});schedule();dialog.close();}),button('이름 변경',()=>{const body=modal('배치 이름 변경'),[l,i]=field('이름','text',p.title);i.maxLength=80;body.append(l,button('변경',async()=>{if(!i.value.trim())return;const next={...p,title:i.value.trim()};if(user){const r=await store.savePlan(next);if(r.conflict)throw Error('다른 기기에서 수정했습니다. 다시 열어 주세요.');next.revision=r.revision;}store.saveDraft(user,next);if(project.id===p.id)setProject(next);await projects();}));}),button('삭제',()=>{const body=modal('배치 삭제');body.append(el('p',`“${p.title}”을 삭제합니다. 공유 링크도 중지됩니다.`),button('삭제 확인',async()=>{await saving.catch(()=>{});if(user)await store.deletePlan(p.id);store.removeDraft(user,p.id);if(project.id===p.id)setProject(newProject());await projects();}));}));b.append(card);}if(!user)b.append(button('로그인하고 계정에 저장',login));}
function start(){const b=modal('52A 배치 시작');b.append(el('p','예시 가구와 치수는 제안입니다. 공식 제공 품목이 아닙니다.'));for(const [kind,title]of [['empty','빈집에서 시작'],['life','기본 생활형'],['work','재택근무형']])b.append(button(title,()=>{flush();readonly=false;setProject(newProject(kind));dialog.close();$('.quick-start').hidden=true;viewport.scrollIntoView({block:'center'});schedule();}));b.append(button('내 배치 불러오기',projects));}
async function exports(){const b=modal('내보내기');const m=await import('./planner-export.mjs');b.append(el('p','이미지·PDF는 구매 전 검토용입니다. 치수는 실측으로 확인해 주세요.'));const notes=el('input');notes.type='checkbox';const noteLabel=el('label');noteLabel.append(notes,document.createTextNode(' PDF에 개인 메모 포함'));b.append(noteLabel);b.append(button('평면 PNG 저장',async()=>m.downloadBlob(await m.pngFromSvg(svg),project.title+'.png')),button('3D PNG 저장',async()=>{await show3D();if(mode!=='3d')return;m.downloadBlob(await three.capture(),project.title+'-3D.png');}),button('PDF 저장',async()=>{toast('한글 PDF를 만들고 있습니다.');m.downloadBlob(await m.exportPDF({project:clone(project),floor,svgElement:svg,includeNotes:notes.checked}),project.title+'.pdf');toast('PDF를 만들었습니다.');}),button('편집 파일 저장',()=>m.downloadBlob(new Blob([JSON.stringify(project)],{type:'application/json'}),project.title+'.c14.json')));const [l,input]=field('편집 파일 불러오기','file','');input.accept='.json,application/json';input.onchange=async()=>{try{const f=input.files[0];if(!f)return;if(f.size>500000)throw Error('500KB 이하 파일을 선택해 주세요.');const p=validateProject(JSON.parse(await f.text()));flush();readonly=false;setProject({...p,id:uid(),revision:0,title:p.title.slice(0,65)+' · 가져오기'});schedule();dialog.close();toast('새 배치안으로 불러왔습니다.');}catch(e){fail(e);}};b.append(l);}
async function share(){if(readonly){if(!user)return login();const copy={...clone(project),id:uid(),revision:0,title:project.title.slice(0,65)+' · 사본'};readonly=false;setProject(copy);history=[];window.history.replaceState(null,'','planner.html');await cloudSave();return toast('내 배치로 복사했습니다.');}if(!user)return login();await cloudSave();const b=modal('가족에게 배치 공유');b.append(el('p','링크를 아는 사람은 로그인 없이 볼 수 있습니다. 원본을 수정할 수 없으며 내 배치로 복사할 수 있습니다.'));const label=el('label'),details=el('input');details.type='checkbox';label.append(details,document.createTextNode(' 개인 메모와 제품 링크도 포함'));b.append(label);const current=await store.ownShare(project.id);if(current)b.append(el('p','현재 공유 중입니다. 아래 버튼으로 최신 배치를 반영할 수 있습니다.'));b.append(button(current?'공유 내용 업데이트':'공유 링크 만들기',async()=>{const id=await store.sharePlan(project.id,details.checked),url=new URL('planner.html',location.href);url.hash='share='+id;const [l,i]=field('공유 링크','text',url.href);i.readOnly=true;b.append(l,button('링크 복사',async()=>{await navigator.clipboard.writeText(url.href);toast('링크를 복사했습니다.');}),button('휴대폰 공유',async()=>{if(navigator.share){try{await navigator.share({title:project.title,url:url.href});}catch(e){if(e.name!=='AbortError')throw e;}}else{await navigator.clipboard.writeText(url.href);toast('링크를 복사했습니다.');}}));}),button('공유 중지',async()=>{await store.stopShare(project.id);dialog.close();toast('공유를 중지했습니다. 기존 링크는 열리지 않습니다.');}));}
function menu(){const b=modal(readonly?'공유 배치 · 보기 전용':'배치 메뉴');for(const [name,fn]of [['내 배치',projects],['저장',cloudSave],['내보내기',exports],[readonly?'내 배치로 복사':'공유',share],['로그인·계정',login],['새 배치',start],['거리 측정',()=>{dialog.close();show2D();measure=!measure;measurePoints=[];toast(measure?'두 지점을 누르면 거리를 표시합니다.':'거리 측정 종료');}],['벽 높이 전환',async()=>{dialog.close();lowWalls=!lowWalls;await show3D();}],['설정·도면 출처',settings]])b.append(button(name,fn));}
function settings(){const b=modal('설정·도면 출처');b.append(el('p',floor.source),el('p','벽·문 위치는 제공 도면을 정리한 초안입니다. 천장·창 높이와 마감 색상은 시각화용이며, 구매 전 실측해 주세요.'));const [l,i]=field('천장 높이 (cm) · 기본 230cm 가정','number',project.ceilingHeight/10);i.min=200;i.max=400;b.append(l,button('적용',()=>{const h=Number(i.value)*10;if(h<2000||h>4000||!Number.isFinite(h))throw Error('200~400cm로 입력해 주세요.');change(()=>project.ceilingHeight=h);dialog.close();}));const a=el('a','52A 원본 설계도 PDF ↗');a.href='assets/c14-52a-drawing.pdf';a.target='_blank';a.rel='noopener';b.append(a);}
const actions={menu,catalog:()=>{$('#catalog').classList.add('is-open');$('#inspector').classList.remove('is-open');},inspector:()=>$('#inspector').classList.add('is-open'),'catalog-close':()=>$('#catalog').classList.remove('is-open'),'inspector-close':()=>$('#inspector').classList.remove('is-open'),'close-dialog':()=>dialog.close(),undo:()=>{if(readonly||!history.length)return;future.push(clone(project));const rev=project.revision;project=history.pop();project.revision=rev;refresh();schedule();},redo:()=>{if(readonly||!future.length)return;history.push(clone(project));const rev=project.revision;project=future.pop();project.revision=rev;refresh();schedule();},save:cloudSave,projects,export:exports,share,login,'view-2d':show2D,'view-3d':show3D,'zoom-in':()=>zoom(.8),'zoom-out':()=>zoom(1.25),fit,measure:()=>{show2D();measure=!measure;measurePoints=[];toast(measure?'두 지점을 눌러 거리를 측정하세요.':'거리 측정 종료');render();},walls:async()=>{lowWalls=!lowWalls;await show3D();},start,settings,'custom-furniture':()=>beginAdd('custom')};
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b){const fn=actions[b.dataset.action];if(fn)Promise.resolve().then(fn).catch(fail);}const c=e.target.closest('[data-category]');if(c){category=c.dataset.category;$$('[data-category]').forEach(b=>{b.classList.toggle('active',b===c);b.setAttribute('aria-selected',String(b===c));});renderCatalog();}});
$('#catalog-search').oninput=renderCatalog;$('#room-select').replaceChildren(new Option('집 전체','all'),...floor.rooms.map(r=>new Option(r.name,r.id)));$('#room-select').onchange=focusRoom;$('#doors').onchange=render;$('#cad-overlay').onchange=render;$('#project-name').maxLength=80;$('#project-name').onchange=e=>{if(!e.target.value.trim()){e.target.value=project.title;return;}change(()=>project.title=e.target.value.trim());};
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||dialog.open)return;if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();e.shiftKey?actions.redo():actions.undo();}if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();cloudSave().catch(fail);}if(e.key==='Escape'){pendingType=null;positioning=false;measure=false;$('#catalog').classList.remove('is-open');$('#inspector').classList.remove('is-open');}if(e.key==='Delete'&&selectedItem()&&!selectedItem().locked)change(()=>{project.items=project.items.filter(i=>i.id!==selected);selected=null;});});
window.addEventListener('online',()=>cloudSave().catch(fail));window.addEventListener('pagehide',()=>{clearTimeout(localTimer);localSave();});
store.auth.auth.onAuthStateChange((event,s)=>{const next=s?.user||null;if(event==='INITIAL_SESSION')return;if(next?.id===user?.id)return;const previous=user;authEpoch++;clearTimeout(localTimer);clearTimeout(cloudTimer);user=next;$$('[data-action="login"]').forEach(b=>b.textContent=user?'내 계정':'로그인');if(previous&&!next&&!readonly){setProject(newProject());status('로그아웃됨 · 새 배치');}else if(user&&!readonly){project.id=uid();project.revision=0;status('로그인됨 · 저장 버튼으로 계정에 보관');}});
async function init(){try{user=(await store.session())?.user||null;}catch{}const sid=new URLSearchParams(location.hash.slice(1)).get('share');if(sid){readonly=true;try{const data=await store.getShare(sid);if(!data)throw Error('공유가 중지되었거나 존재하지 않는 링크입니다.');setProject({...validateProject(data),id:uid(),revision:0});$('.quick-start').hidden=true;$$('[data-action="share"]').forEach(b=>b.textContent='내 배치로 복사');}catch(e){const b=modal('공유 배치를 열 수 없습니다');b.append(el('p',e.message),button('새 배치 시작',()=>{window.history.replaceState(null,'','planner.html');readonly=false;dialog.close();start();}));}}else{const ds=store.drafts(user);if(ds.length){try{setProject(validateProject(ds[0]));$('.quick-start').hidden=true;}catch{setProject(newProject());}}else setProject(newProject());}$$('[data-action="login"]').forEach(b=>b.textContent=user?'내 계정':'로그인');renderCatalog();refresh();}
init();
