export function downloadBlob(blob,filename){if(!blob)throw Error('파일을 만들지 못했습니다.');const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=filename;a.textContent=filename+' 다운로드';a.className='download-ready';(document.querySelector('dialog[open] #dialog-body')||document.body).append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(u);a.remove();},120000);}
export async function pngFromSvg(svg){const c=svg.cloneNode(true);c.removeAttribute('hidden');for(const image of c.querySelectorAll('image')){const response=await fetch(new URL(image.getAttribute('href'),location.href));if(!response.ok)throw Error('원도 벽선 로드 실패');image.setAttribute('href','data:image/svg+xml;charset=utf-8,'+encodeURIComponent(await response.text()));}const v=svg.viewBox.baseVal,w=Math.round(2000*v.width/Math.max(v.width,v.height)),h=Math.round(2000*v.height/Math.max(v.width,v.height));c.setAttribute('width',w);c.setAttribute('height',h);c.setAttribute('xmlns','http://www.w3.org/2000/svg');return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(im,0,0,w,h);canvas.toBlob(b=>b?resolve(b):reject(Error('이미지 생성 실패')),'image/png');};im.onerror=()=>reject(Error('평면 이미지를 만들지 못했습니다.'));im.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(new XMLSerializer().serializeToString(c));});}
export async function exportPDF({project,floor,svgElement,includeNotes=false}){
 await import('./assets/planner-vendor/jspdf.umd.min.js');const {jsPDF}=globalThis.jspdf;if(!jsPDF)throw Error('PDF 도구 로드 실패');
 const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),response=await fetch('./assets/planner-vendor/NotoSansKR-Regular.ttf');if(!response.ok)throw Error('한글 글꼴을 불러오지 못했습니다. 다시 시도해 주세요.');
 const bytes=new Uint8Array(await response.arrayBuffer());let binary='';for(let k=0;k<bytes.length;k+=8192)binary+=String.fromCharCode(...bytes.subarray(k,k+8192));doc.addFileToVFS('Noto.ttf',btoa(binary));doc.addFont('Noto.ttf','Noto','normal');doc.setFont('Noto');doc.setFontSize(18);doc.text(project.title,14,16);doc.setFontSize(9);doc.text(`${floor.name} · ${floor.version} · ${new Date().toLocaleDateString('ko-KR')}`,14,24);
 const png=await pngFromSvg(svgElement),im=await createImageBitmap(png),scale=Math.min(269/im.width,155/im.height);doc.addImage(new Uint8Array(await png.arrayBuffer()),'PNG',(297-im.width*scale)/2,31,im.width*scale,im.height*scale);im.close();doc.setFontSize(8);doc.text('도면 제공: 입주민 재재님 · 시각화용 초안 · 구매·시공 전 현장 실측이 필요합니다.',14,202);
 doc.addPage();doc.setFontSize(15);doc.text('가구 목록 · 가로 × 깊이 × 높이',14,18);doc.setFontSize(10);let y=30;
 for(const [n,i]of project.items.entries()){const lines=doc.splitTextToSize(`${n+1}. ${i.name} — ${i.w/10} × ${i.d/10} × ${i.h/10} cm${includeNotes&&i.note?'\n메모: '+i.note:''}`,265);for(const line of lines){if(y>192){doc.addPage();y=18;}doc.text(line,14,y);y+=6;}y+=4;}
 return doc.output('blob');
}
