const MM = .001;
export function fitFurniture(group,w,h,d,T){
  group.position.set(0,0,0);group.rotation.set(0,0,0);
  const bounds=new T.Box3().setFromObject(group),size=bounds.getSize(new T.Vector3()),center=bounds.getCenter(new T.Vector3());
  if(![w,h,d,size.x,size.y,size.z].every(n=>Number.isFinite(n)&&n>0))throw Error('가구 치수 오류');
  group.children.forEach(o=>{o.position.x-=center.x;o.position.y-=bounds.min.y;o.position.z-=center.z;});group.scale.set(w/size.x,h/size.y,d/size.z);
}

export async function create3D(container, floor, onSelect = () => {}, onViewChange = () => {}, onMove = () => {}) {
  const T = await import('./assets/planner-vendor/three.module.js');
  const {OrbitControls} = await import('./assets/planner-vendor/OrbitControls.js?v=2');
  const scene = new T.Scene();scene.background=new T.Color('#e9e8e3');
  const camera=new T.PerspectiveCamera(38,1,.03,150);
  const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});
  renderer.setPixelRatio(Math.min(devicePixelRatio||1,innerWidth<761?1.5:2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.outputColorSpace=T.SRGBColorSpace;
  renderer.domElement.setAttribute('aria-label',floor.name+' 3D 공간. 선택한 가구를 끌어 이동할 수 있습니다.');container.replaceChildren(renderer.domElement);
  const controls=new OrbitControls(camera,renderer.domElement);controls.maxPolarAngle=Math.PI*.49;controls.minDistance=.6;controls.maxDistance=50;controls.enableDamping=false;controls.screenSpacePanning=true;
  const root=new T.Group(),furniture=new T.Group();scene.add(root,furniture);
  const sky=new T.HemisphereLight('#f5f5ee','#9b8b79',2);scene.add(sky);
  const sun=new T.DirectionalLight('#fff1d7',3.6);sun.position.set(-7,12,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-14,right:14,top:14,bottom:-14,near:.1,far:45});sun.shadow.bias=-.0002;sun.shadow.normalBias=.035;sun.shadow.radius=4;scene.add(sun);
  const fill=new T.DirectionalLight('#d6e5ff',.8);fill.position.set(8,5,-7);scene.add(fill);
  const bounds=floor.bounds,center=[(bounds[0]+bounds[2])/2,(bounds[1]+bounds[3])/2];
  const world=(x,y)=>[(x-center[0])*MM,(y-center[1])*MM];
  let project={items:[]},selected=null,lowWalls=true,viewMode='overview',disposed=false,drag=null,down=null,selectionBox=null;
  const meshes=new Map(),textures=[],materials=new Map(),wallMeshes=[];
  // Procedural finishes are illustrations, not manufacturer material samples.
  function texture(kind){const canvas=document.createElement('canvas');canvas.width=canvas.height=512;const c=canvas.getContext('2d');let seed=17;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
    c.fillStyle=kind==='oak'?'#cbb18a':kind==='fabric'?'#ddd8ce':'#d5d2ca';c.fillRect(0,0,512,512);
    if(kind==='oak'){for(let col=0;col<8;col++){const x=col*64;c.fillStyle=`rgba(75,44,15,${.025+random()*.09})`;c.fillRect(x,0,63,512);c.fillStyle='#aa927266';c.fillRect(x,0,1,512);for(let j=0;j<85;j++){c.strokeStyle=`rgba(89,58,25,${random()*.14})`;c.beginPath();const gx=x+random()*63;c.moveTo(gx,0);c.bezierCurveTo(gx+3,150,gx-3,350,gx,512);c.stroke();}c.fillStyle='#90765055';c.fillRect(x,Math.floor(random()*512),64,1);}}
    else{for(let n=0;n<22000;n++){const v=random()>.5?'255,255,255':'60,50,40';c.fillStyle=`rgba(${v},${random()*.11})`;c.fillRect(random()*512,random()*512,kind==='fabric'?1:2,kind==='fabric'?3:2);}if(kind==='tile'){c.strokeStyle='#aaa69e';c.lineWidth=2;c.strokeRect(0,0,512,512);}}
    const tex=new T.CanvasTexture(canvas);tex.colorSpace=T.SRGBColorSpace;tex.wrapS=tex.wrapT=T.RepeatWrapping;tex.repeat.set(kind==='oak'?3:kind==='fabric'?3:5,kind==='oak'?3:kind==='fabric'?3:5);tex.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());textures.push(tex);return tex;}
  const glassMaterial=new T.MeshStandardMaterial({color:'#c4d7da',transparent:true,opacity:.22,roughness:.15,metalness:.1,side:T.DoubleSide});materials.set('glass',glassMaterial);
  const maps={oak:texture('oak'),fabric:texture('fabric'),tile:texture('tile')};
  function material(color,finish='plain'){const key=color+finish;if(!materials.has(key))materials.set(key,new T.MeshStandardMaterial({color,roughness:finish==='metal'?.28:finish==='fabric'?.95:.72,metalness:finish==='metal'?.7:0,map:maps[finish]||null}));return materials.get(key);}
  function rounded(w,h,d,r=.04){r=Math.max(.001,Math.min(r,w/4,h/4,d/4));const shape=new T.Shape(),x=-w/2+r,y=-h/2+r;shape.moveTo(x,y);shape.lineTo(x+w-2*r,y);shape.lineTo(x+w-2*r,y+h-2*r);shape.lineTo(x,y+h-2*r);shape.closePath();const g=new T.ExtrudeGeometry(shape,{depth:d-2*r,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:r,bevelThickness:r,curveSegments:4});g.translate(0,0,-d/2+r);g.computeVertexNormals();return g;}
  function box(parent,w,h,d,x,y,z,color='#ece8e0',finish='plain',radius=0){const m=new T.Mesh(radius?rounded(w,h,d,radius):new T.BoxGeometry(w,h,d),material(color,finish));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
  function cylinder(parent,r,h,x,y,z,color,finish='plain'){const m=new T.Mesh(new T.CylinderGeometry(r,r,h,32),material(color,finish));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
  function clear(group){group.traverse(o=>o.geometry?.dispose());group.clear();}
  let wallPolygons=[];
  if(floor.version!=='52a-v1'){try{const response=await fetch(`assets/planner-${floor.version.split('-')[0]}-cad-walls.svg`);if(response.ok){const doc=new DOMParser().parseFromString(await response.text(),'image/svg+xml');wallPolygons=[...doc.querySelectorAll('polyline')].map(e=>e.getAttribute('points').trim().split(/\s+/).map(p=>p.split(',').map(Number))).filter(p=>p.length>=4&&p[0][0]===p.at(-1)[0]&&p[0][1]===p.at(-1)[1]);}}catch{}}
  function roomShape(points){const shape=new T.Shape();points.forEach(([x,y],n)=>{const [wx,wz]=world(x,y);n?shape.lineTo(wx,-wz):shape.moveTo(wx,-wz);});shape.closePath();return shape;}
  function architecture(){clear(root);wallMeshes.length=0;
    const ground=new T.Mesh(new T.PlaneGeometry(100,100),material('#e9e8e3'));ground.rotation.x=-Math.PI/2;ground.position.y=-.22;ground.receiveShadow=true;root.add(ground);
    for(const r of floor.rooms){const shape=roomShape(r.polygon),wet=/bath|balcony|outdoor|entry/.test(r.id);const slab=new T.Mesh(new T.ExtrudeGeometry(shape,{depth:.16,bevelEnabled:false}),material('#f1eee8'));slab.rotation.x=-Math.PI/2;slab.position.y=-.16;slab.receiveShadow=true;root.add(slab);const top=new T.Mesh(new T.ShapeGeometry(shape),material(wet?'#e4e4df':'#f4e6cc',wet?'tile':'oak'));top.rotation.x=-Math.PI/2;top.position.y=.002;top.receiveShadow=true;root.add(top);}
    const height=(lowWalls?.65:project.ceilingHeight*MM)||2.3;
    if(wallPolygons.length){for(const pts of wallPolygons){const m=new T.Mesh(new T.ExtrudeGeometry(roomShape(pts),{depth:height,bevelEnabled:false}),material('#faf8f2'));m.rotation.x=-Math.PI/2;m.castShadow=m.receiveShadow=true;root.add(m);wallMeshes.push(m);}}
    else for(const w of floor.walls){const [ax,az]=world(...w.a),[bx,bz]=world(...w.b),len=Math.hypot(bx-ax,bz-az);const m=box(root,len,height,w.thickness*MM,(ax+bx)/2,height/2,(az+bz)/2,'#faf8f2');m.rotation.y=-Math.atan2(bz-az,bx-ax);wallMeshes.push(m);const trim=box(root,len,.075,w.thickness*MM+.018,(ax+bx)/2,.038,(az+bz)/2,'#c9c1b4');trim.rotation.y=m.rotation.y;}
    for(const w of floor.windows){const [ax,az]=world(...w.a),[bx,bz]=world(...w.b),length=Math.hypot(bx-ax,bz-az);const group=new T.Group();group.position.set((ax+bx)/2,0,(az+bz)/2);group.rotation.y=-Math.atan2(bz-az,bx-ax);root.add(group);const sill=lowWalls?.4:.85,h=lowWalls?.18:1.3;box(group,length,.04,.11,0,sill,0,'#858c8c','metal');box(group,length,.04,.11,0,sill+h,0,'#858c8c','metal');for(const x of [-length/2,0,length/2])box(group,.035,h,.08,x,sill+h/2,0,'#858c8c','metal');const glass=new T.Mesh(new T.PlaneGeometry(length,h),glassMaterial);glass.position.set(0,sill+h/2,0);group.add(glass);}
    for(const f of floor.fixtures){const [x,z]=world(f.x,f.y),group=new T.Group();group.position.set(x,0,z);root.add(group);box(group,f.w*MM,f.h*MM,f.d*MM,0,f.h*MM/2,0,'#dedbd2');box(group,f.w*MM+.02,.035,f.d*MM+.02,0,f.h*MM+.015,0,'#f8f5ee','tile');for(let k=0;k<Math.max(1,Math.round(f.w/600));k++)box(group,.015,f.h*MM*.8,.006,-f.w*MM/2+(k+1)*.55,f.h*MM*.48,f.d*MM/2+.004,'#b9b6ae');}
  }
  function addItem(i){const [x,z]=world(i.x,i.y),g=new T.Group();g.position.set(x,0,z);g.rotation.y=-i.rotation*Math.PI/180;g.userData.itemId=i.id;const w=i.w*MM,d=i.d*MM,h=i.h*MM;
    const b=(bw,bh,bd,bx,by,bz,color=i.color,finish='plain',r=0)=>box(g,bw,bh,bd,bx,by,bz,color,finish,r);
    const legs=(top=.7)=>{for(const sx of [-1,1])for(const sz of [-1,1])b(Math.min(.055,w*.06),top,Math.min(.055,d*.06),sx*w*.4,top/2,sz*d*.4,'#574c3f');};
    if(i.type.includes('sofa')){legs(h*.15);b(w,h*.2,d,0,h*.25,0,i.color,'fabric',.035);b(w*.94,h*.52,d*.19,0,h*.73,-d*.4,i.color,'fabric',.065);for(const sx of [-1,1])b(w*.09,h*.52,d,sx*w*.455,h*.52,0,i.color,'fabric',.055);const seats=Math.max(2,Math.round(w/.85));for(let k=0;k<seats;k++){const cx=-w*.4+(k+.5)*w*.8/seats;b(w*.8/seats-.014,h*.22,d*.72,cx,h*.44,d*.075,i.color,'fabric',.055);const pillow=b(w*.8/seats-.035,h*.34,d*.13,cx,h*.73,-d*.25,'#dfd6c7','fabric',.06);pillow.rotation.x=-.12;}if(i.type==='corner-sofa')b(w*.32,h*.24,d*.48,w*.28,h*.43,d*.24,i.color,'fabric',.05);}
    else if(i.type==='bed'){legs(h*.14);b(w,h*.22,d,0,h*.24,0,i.color,'fabric',.04);b(w,h*.95,d*.07,0,h*.475,-d*.465,i.color,'fabric',.045);b(w*.96,h*.23,d*.9,0,h*.465,d*.02,'#faf8ef','fabric',.065);b(w*.97,h*.07,d*.62,0,h*.605,d*.15,'#b8c0b1','fabric',.035);for(const sx of [-1,1])b(w*.41,h*.1,d*.19,sx*w*.245,h*.62,-d*.28,'#fffdf8','fabric',.06);}
    else if(['coffee','dining','desk','vanity','round-table'].includes(i.type)){legs(h*.92);if(i.type==='round-table'){const top=cylinder(g,w/2,h*.08,0,h*.96,0,'#ece0c9','oak');top.scale.z=d/w;}else b(w,h*.08,d,0,h*.96,0,'#eadac0','oak',.018);if(i.type==='vanity'){const mirror=b(w*.65,h*.65,.025,0,h*1.28,-d*.44,'#c1d0d0','metal',.025);mirror.scale.y=.5;mirror.position.y=h*.8;}}
    else if(i.type==='chair'){legs(h*.46);b(w,.07,d*.9,0,h*.48,0,i.color,'fabric',.028);b(w,h*.45,.07,0,h*.755,-d*.4,i.color,'fabric',.035);}
    else if(['washer','dryer'].includes(i.type)){b(w,h,d,0,h/2,0,'#eeefeb','metal',.035);const ring=cylinder(g,Math.min(w,h)*.32,.035,0,h*.48,d/2+.008,'#474e50','metal');ring.rotation.x=Math.PI/2;const glass=cylinder(g,Math.min(w,h)*.24,.04,0,h*.48,d/2+.027,'#192b32','metal');glass.rotation.x=Math.PI/2;b(w*.5,h*.07,.015,-w*.15,h*.87,d/2+.015,'#404a4d');}
    else if(i.type==='fridge'){b(w,h,d,0,h/2,0,'#ccd0cd','metal',.025);b(.009,h*.96,.01,0,h*.5,d/2+.005,'#66716f');for(const sx of [-1,1])b(.025,h*.25,.025,sx*w*.06,h*.6,d/2+.02,'#69716e','metal',.009);}
    else if(['wardrobe','drawers','nightstand','bookshelf','tv'].includes(i.type)){const n=i.type==='wardrobe'?Math.max(2,Math.round(w/.6)):i.type==='bookshelf'?4:3;b(w,h,d,0,h/2,0,i.color,'oak',.01);if(i.type==='bookshelf'){for(let k=0;k<4;k++){b(w*.88,h*.2,d*.035,0,h*(k+.5)/4,d/2+.001,'#645c4f');for(let j=0;j<4;j++)b(w*.13,h*.15,d*.62,-w*.32+j*w*.17,h*(k+.5)/4,d*.14,['#b8b2a1','#b88564','#7c908e','#d3c4a4'][j],'plain',.003);}}else for(let k=0;k<n;k++){if(i.type==='wardrobe'){b(.012,h*.94,.012,-w/2+(k+1)*w/n,h/2,d/2+.003,'#8f8779');b(.014,h*.15,.025,-w/2+(k+.85)*w/n,h*.45,d/2+.018,'#4e514b','metal');}else{b(w*.94,.008,.012,0,h*(k+1)/n,d/2+.003,'#8f8779');b(w*.2,.016,.025,0,h*(k+.55)/n,d/2+.015,'#4e514b','metal');}}}
    else b(w,h,d,0,h/2,0,i.color,'plain',.025);
    fitFurniture(g,w,h,d,T);g.position.set(x,0,z);g.rotation.y=-i.rotation*Math.PI/180;furniture.add(g);meshes.set(i.id,g);
  }
  function highlight(){if(selectionBox){scene.remove(selectionBox);selectionBox.geometry.dispose();selectionBox.material.dispose();selectionBox=null;}const g=meshes.get(selected);if(g){selectionBox=new T.BoxHelper(g,0x347c87);selectionBox.material.depthTest=false;selectionBox.material.transparent=true;selectionBox.material.opacity=.65;scene.add(selectionBox);}}
  function render(){if(disposed)return;selectionBox?.update();renderer.render(scene,camera);onViewChange();}
  function fit(){viewMode='overview';const span=Math.max(bounds[2],bounds[3])*MM,dist=span/(2*Math.tan(camera.fov*Math.PI/360)*Math.min(1,camera.aspect));controls.target.set(0,0,0);camera.position.set(dist*.38,dist*.7,dist*.62);controls.update();render();}
  function focusRoom(room){if(!room)return fit();viewMode='room';const xs=room.polygon.map(p=>p[0]),ys=room.polygon.map(p=>p[1]),[x,z]=world((Math.min(...xs)+Math.max(...xs))/2,(Math.min(...ys)+Math.max(...ys))/2),span=Math.max(Math.max(...xs)-Math.min(...xs),Math.max(...ys)-Math.min(...ys))*MM,dist=Math.max(3,span/Math.min(1,camera.aspect));controls.target.set(x,.45,z);camera.position.set(x+dist*.55,dist*.8,z+dist*.7);controls.update();render();}
  const ray=new T.Raycaster(),pointer=new T.Vector2(),groundPlane=new T.Plane(new T.Vector3(0,1,0),0);
  function rayAt(e){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);}
  function hitAt(e){rayAt(e);const hit=ray.intersectObjects([...meshes.values()],true)[0];let o=hit?.object;while(o&&!o.userData.itemId)o=o.parent;return o?.userData.itemId;}
  renderer.domElement.addEventListener('pointerdown',e=>{if(drag)return;down={x:e.clientX,y:e.clientY};const id=hitAt(e),i=project.items.find(i=>i.id===id);if(e.button!==0||id!==selected||!i||i.locked||project.readonly)return;const point=ray.ray.intersectPlane(groundPlane,new T.Vector3());if(!point)return;const g=meshes.get(id);drag={id,pointerId:e.pointerId,start:g.position.clone(),offset:point.sub(g.position),moved:false};controls.enabled=false;renderer.domElement.setPointerCapture(e.pointerId);e.stopImmediatePropagation();},true);
  renderer.domElement.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointerId)return;rayAt(e);const p=ray.ray.intersectPlane(groundPlane,new T.Vector3());if(p){p.sub(drag.offset);const g=meshes.get(drag.id);g.position.set(p.x,0,p.z);drag.moved=Math.hypot(e.clientX-down.x,e.clientY-down.y)>4;render();}},true);
  function endDrag(e,cancel=false){if(drag&&e.pointerId!==drag.pointerId)return;if(drag){const d=drag,g=meshes.get(d.id);drag=null;controls.enabled=true;if(cancel||!d.moved)g.position.copy(d.start);else onMove(d.id,Math.round(g.position.x/MM+center[0]),Math.round(g.position.z/MM+center[1]));render();return;}if(!cancel&&down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<5)onSelect(hitAt(e)||null);}
  renderer.domElement.addEventListener('pointerup',e=>endDrag(e));renderer.domElement.addEventListener('pointercancel',e=>endDrag(e,true));
  const resize=()=>{const r=container.getBoundingClientRect();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height),false);camera.aspect=Math.max(1,r.width)/Math.max(1,r.height);camera.updateProjectionMatrix();if(viewMode==='overview')fit();else render();};const observer=new ResizeObserver(resize);observer.observe(container);
  const api={update(next,id=selected){project=next;selected=id;architecture();clear(furniture);meshes.clear();project.items.forEach(addItem);highlight();render();},setSelection(id){selected=id;highlight();render();},projectPoint(id){const g=meshes.get(id),i=project.items.find(i=>i.id===id);if(!g||!i)return null;const p=new T.Vector3(g.position.x,i.h*MM,g.position.z).project(camera),r=container.getBoundingClientRect();return{x:(p.x+1)*r.width/2,y:(1-p.y)*r.height/2};},focusRoom,setLowWalls(v){lowWalls=!!v;architecture();render();},setView(mode){if(mode==='overview')fit();else if(mode==='top'){controls.target.set(0,0,0);camera.position.set(0,Math.max(bounds[2],bounds[3])*MM/Math.min(1,camera.aspect)*1.5,.001);controls.update();render();}else{const room=floor.rooms.find(r=>r.id==='living'),xs=room.polygon.map(p=>p[0]),ys=room.polygon.map(p=>p[1]),[x,z]=world((Math.min(...xs)+Math.max(...xs))/2,(Math.min(...ys)+Math.max(...ys))/2);controls.target.set(x,1.35,z-1.8);camera.position.set(x,1.6,z+1.4);controls.update();render();}viewMode=mode;},setLight(evening){sun.color.set(evening?'#ffc581':'#fff1d7');sun.intensity=evening?2:3.6;sky.intensity=evening?1:2;renderer.toneMappingExposure=evening?1:1.15;render();},resize,async capture(){const old=renderer.getSize(new T.Vector2()),ratio=renderer.getPixelRatio(),scale=2000/Math.max(old.x,old.y);try{renderer.setPixelRatio(1);renderer.setSize(Math.round(old.x*scale),Math.round(old.y*scale),false);render();return await new Promise(resolve=>renderer.domElement.toBlob(resolve,'image/png'));}finally{renderer.setPixelRatio(ratio);renderer.setSize(old.x,old.y,false);render();}},dispose(){disposed=true;observer.disconnect();controls.dispose();clear(root);clear(furniture);if(selectionBox){selectionBox.geometry.dispose();selectionBox.material.dispose();}for(const m of materials.values())m.dispose();textures.forEach(t=>t.dispose());renderer.dispose();container.replaceChildren();}};
  controls.addEventListener('change',render);api.update(project);resize();fit();return api;
}
